# Site settings
title: Andrew Shapro
header: Software Engineer
email: me@andrewshapro.com
author: Andrew Shapro
description: > # this means to ignore newlines until "baseurl:"
  Personal website for Andrew Shapro
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andrewshapro.com" # the base hostname & protocol for your site
github_username:  abramz
bitbucket_username:  abramz

# Build settings
markdown: kramdown
